apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitlab-runner
  namespace: default # Ini akan diinstal di namespace 'default'
spec:
  interval: 30m
  chart:
    spec:
      chart: gitlab-runner
      sourceRef:
        kind: HelmRepository
        name: gitlab # Harus sama dengan nama di file 1
      version: "0.51.0"
  values:
    gitlabUrl: http://gitlab.domain-anda.com/ # <-- GANTI INI
    runnerRegistrationToken: "glrt-c3wpu5Szox3kOVKc2FB52G86MQpwOmoKdDozCnU6Mw8.01.1702euly7" # <-- GANTI INI
    
    runners:
      tags: "openshift, flux, ocp-local"

    # --- INI BAGIAN PENTING UNTUK HTTP ---
    envVars:
      - name: GIT_SSL_NO_VERIFY
        value: "true"
    # --------------------------------------
        
    securityContext:
      runAsUser: 1001
      fsGroup: 1001
